name: Pylint

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version used in example"
        default: '1.0'
        type: choice
        options:
        - '1.0'
        - '5.0'
        - '4.1'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Show test parameters
      run: |
        echo ${{ matrix.python-version }}
        echo "${{ matrix.python-version }}"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
